Repository TradeWebProject/trade_web_project_BE, pull requests merged in 2024-06, with the labels that each got.

#2 test 파일 생성
  .idea/workspace.xml
  testfile
Labels: feat

#4 Feature/minkyung/#2
  .idea/misc.xml
  .idea/trade_web_project_BE.iml
  .idea/workspace.xml
  test.java
Labels: feat

#6 [ setting ] 프로젝트 초기 세팅
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/workspace.xml
  test.java
  trade-web-project/.gitignore
  trade-web-project/build.gradle
  trade-web-project/gradle/wrapper/gradle-wrapper.jar
  trade-web-project/gradle/wrapper/gradle-wrapper.properties
  trade-web-project/gradlew
  trade-web-project/gradlew.bat
  trade-web-project/settings.gradle
  trade-web-project/src/main/java/com/github/tradewebproject/TradeWebProjectApplication.java
  trade-web-project/src/main/java/com/github/tradewebproject/config/SecurityConfig.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/UserController.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/User.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/UserRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/UserService.java
  trade-web-project/src/main/resources/application.yml
  trade-web-project/src/test/java/com/github/tradewebproject/TradeWebProjectApplicationTests.java
Labels: setting

#8 [ feat ] 유저 로그인, 로그아웃, 회원가입 작업 수행
  .idea/gradle.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/ErrorMsg.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/JwtAccessDeniedHandler.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/JwtAuthenticationFilter.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/JwtExceptionFilter.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/JwtProvider.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/ResponseToken.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/Token.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/User/Deleted.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/User/NewUserDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/User/Role.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/User/UserDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/TradeWebProjectApplication.java
  trade-web-project/src/main/java/com/github/tradewebproject/config/AuditingConfig.java
  trade-web-project/src/main/java/com/github/tradewebproject/config/AuditorAwareImpl.java
  trade-web-project/src/main/java/com/github/tradewebproject/config/SecurityConfig.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/UserController.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/UserResponse.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/TokenEntity.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/User.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Jwt/TokenJpaRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Jwt/TokenRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Jwt/TokenRepositoryImpl.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/User/UserJpaRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/User/UserRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/User/UserRepositoryImpl.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/UserRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Jwt/JwtService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Jwt/JwtServiceImpl.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/User/UserNotFoundException.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/User/UserService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/User/UserServiceImpl.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/UserService.java
  trade-web-project/src/main/resources/application.yml
Labels: feat

#10 [ setting ] SDK, Gradle JVM 변경
  .idea/gradle.xml
  .idea/misc.xml
  .idea/workspace.xml
  trade-web-project/src/main/java/com/github/tradewebproject/config/SecurityConfig.java
Labels: setting

#16 [ setting ] deploy 세팅
  .idea/modules.xml
  .idea/modules/trade-web-project.main.iml
  .idea/workspace.xml
  logs/server.log
  trade-web-project/build.gradle
  trade-web-project/src/main/resources/application-dev.yml
  trade-web-project/src/main/resources/application-local.yml
  trade-web-project/src/main/resources/application-prod.yml
  trade-web-project/src/main/resources/logback-spring-dev.xml
  trade-web-project/src/main/resources/logback-spring-local.xml
  trade-web-project/src/main/resources/logback-spring-prod.xml
Labels: feat, setting

#20 [ feat ] 마이페이지 , 상품 등록
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/ProductDTO.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/ProductPageResponseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/ProductResponseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/User/getUserDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/ProductController.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/Product.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/ProductImage.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Product/ProductRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Product/ProductService.java
  trade-web-project/src/main/java/com/github/tradewebproject/util/MultipartFileResource.java
Labels: feat, fix

#26 [ feat ] 상품 구매 기능 구현 , 구매 상품 조회 기능 구현 (userId)
  .idea/modules/trade-web-project.main.iml
  .idea/workspace.xml
  logs/server.log
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Purchase/PurchaseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Purchase/PurchasePageDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Purchase/PurchaseRequestDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/PurchaseController.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/Purchase.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Purchase/PurchaseRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Purchase/PurchaseService.java
Labels: feat

#35 [ feat ] gitignore 추가
  .idea/workspace.xml
  trade-web-project/.gitignore
Labels: bug, feat

#38 [ fix ] 멀티 파일관련 코드 추가
  trade-web-project/src/main/resources/application-prod.yml
Labels: feat, fix

#44 [ feat ] workspace 제거, 상품 검색 구현 (기능추가예정)
  .idea/workspace.xml
  logs/server.log
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/DetailProductDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/ProductDTO.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/ProductController.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Product/ProductRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Product/ProductService.java
Labels: feat, remove

#45 [ remove ] workspace.xml, server.log 캐시 삭제
  .idea/workspace.xml
  logs/server.log
Labels: hotFix, remove

#42 [ feat ] 상품 찜하기 , 상품 구매하기 수정 , 찜한 상품 조회 , 리뷰 작성 , 리뷰 조회 구현
  .idea/modules/trade-web-project.main.iml
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/JwtAuthenticationFilter.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Like/LikePageDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Like/LikeProductDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Like/ProductLikeRequestDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Review/ReviewCreationResponseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Review/ReviewResponseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/LikeProductController.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/ReviewController.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/Like.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/Review.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Like/LikeRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Purchase/PurchaseRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Review/ReviewRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/User/UserRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Like/LikeProductService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Purchase/PurchaseService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Review/ReviewService.java
Labels: feat, fix

#49 [ feat / fix ] 이미지 파일 반환형태 수정 , 상품 찜하기 수정 , 유저 관심사에 따른 상품 조회
  .idea/workspace.xml
  logs/server.log
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/ProductDTO.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/ProductResponseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/config/WebConfig.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/LikeProductController.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/ProductController.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/Product.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Like/LikeRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Product/ProductRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Like/LikeProductService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Product/ProductService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Purchase/PurchaseService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/User/UserServiceImpl.java
Labels: feat, fix

#57 [ fix ] 이미지 처리 url 권한 수정
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/JwtAuthenticationFilter.java
  trade-web-project/src/main/java/com/github/tradewebproject/config/SecurityConfig.java
Labels: fix

#61 [ feat ] 리뷰 조회 , 찜목록 조회 기능 추가
  trade-web-project/src/main/java/com/github/tradewebproject/controller/LikeProductController.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/ReviewController.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Like/LikeRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Review/ReviewRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Like/LikeProductService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Review/ReviewService.java
Labels: fix

#63 login , 조회 기능 권한 수정 , 상품 전체 조회 , 상세 조회 , 리뷰 조회 수정 , 판매자 리뷰 조회 기능 추가
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/JwtAuthenticationFilter.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Jwt/ResponseToken.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Like/LikePageDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/DetailProductDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/ProductResponseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Purchase/PurchaseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Review/ReviewResponseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Review/SellerReviewPageDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Review/SellerReviewResponseDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/LikeProductController.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/ReviewController.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/Purchase.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/Review.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Like/LikeRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Product/ProductRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Purchase/PurchaseRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Review/ReviewRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/User/UserJpaRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Like/LikeProductService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Product/ProductService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Purchase/PurchaseService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Review/ReviewService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/User/UserServiceImpl.java
Labels: feat, fix

#68 [ feat/fix ] 상세 조회 , 상품 등록 , 상품 수정 , 유저 정보 변경 기능 추가
  .gitignore
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Product/DetailProductDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/User/EditUserDto.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/UserController.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/User.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Product/ProductService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/User/UserService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/User/UserServiceImpl.java
Labels: feat, fix

#73 [ feat ] 웹 소켓 관련 코드 + chat_messages + chat_rooms 관련 코드 구현
  .idea/modules/trade-web-project.main.iml
  .idea/modules/trade-web-project.test.iml
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Chat/ChatMessageResponse.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Chat/ChatRoomResponse.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Chat/CreateChatRoomRequest.java
  trade-web-project/src/main/java/com/github/tradewebproject/Dto/Chat/WebSocketMessage.java
  trade-web-project/src/main/java/com/github/tradewebproject/config/Chat/WebSocketConfig.java
  trade-web-project/src/main/java/com/github/tradewebproject/config/Chat/WebSocketHandler.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/Chat/ChatController.java
  trade-web-project/src/main/java/com/github/tradewebproject/controller/Chat/ChatRoomController.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/ChatMessage.java
  trade-web-project/src/main/java/com/github/tradewebproject/domain/ChatRoom.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Chat/ChatMessageRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/repository/Chat/ChatRoomRepository.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Chat/ChatMessageService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Chat/ChatRoomService.java
  trade-web-project/src/main/java/com/github/tradewebproject/service/Chat/ChatService.java
Labels: feat
